### ISSUE TITLE
Support Mermaid diagram and flowchart

### ISSUE THREAD

**Issue by Mogztter** [eshepelyuk/asciidoctor-plantuml.js#49]
https://github.com/knsv/mermaid

**Comment by Mogztter** [comment]
There's at least two issues to integrate Mermaid in this extension using the API:


1. The [`Mermaid#render`](https://github.com/knsv/mermaid/blob/7d3578b31aeea3bc9bbc618dcda57d82574eaffb/src/mermaidAPI.js#L334) function is using a callback but we need to return a result synchronously
2. Mermaid is using the DOM (and d3) to generate an SVG. For instance:

https://github.com/knsv/mermaid/blob/7d3578b31aeea3bc9bbc618dcda57d82574eaffb/src/mermaidAPI.js#L351-L357

**Comment by eshepelyuk** [comment]
Hello @Mogztter 

This issue raises two options in my mind for it's implementation

- Either create a new extension (eg asciidoctor-mermaid.js )
- or rename this extension to `asciidoctor-diagram.js` 

Since as far as I understand `Mermaid` has nothing to do neither with PlantUML nor PlantUML Server.
So I believe before implementing `Mermaid` support - some decision about extension(s) future must be made.
